import DropDownOption from "../models/drop-down-option.model";

export const audioFormatOptions: DropDownOption[] = [
  { value: "mp3", label: "MP3" },
  { value: "aac", label: "AAC" },
  { value: "wav", label: "WAV" },
  { value: "flac", label: "FLAC" },
  { value: "ogg", label: "OGG Vorbis" },
  { value: "opus", label: "Opus" },
  { value: "wma", label: "WMA" },
  { value: "alac", label: "ALAC" },
  { value: "ac3", label: "AC3" },
  { value: "m4a", label: "M4A" },
  { value: "amr", label: "AMR" },
  { value: "aiff", label: "AIFF" },
];

export const imageFormatOptions: DropDownOption[] = [
  { value: "jpg", label: "JPEG" },
  { value: "png", label: "PNG" },
  { value: "gif", label: "GIF" },
  { value: "webp", label: "WebP" },
  { value: "tiff", label: "TIFF" },
  { value: "bmp", label: "BMP" },
  { value: "svg", label: "SVG" },
  { value: "ico", label: "ICO" },
  { value: "heic", label: "HEIC" },
  { value: "raw", label: "RAW" },
  { value: "psd", label: "Photoshop PSD" },
  { value: "avif", label: "AVIF" },
  { value: "eps", label: "EPS" },
  { value: "pcx", label: "PCX" },
  { value: "tga", label: "TGA" },
  { value: "jp2", label: "JPEG 2000" },
  { value: "exr", label: "OpenEXR" },
  { value: "hdr", label: "Radiance HDR" },
  { value: "xcf", label: "GIMP XCF" },
  { value: "ppm", label: "Portable Pixmap" },
];

export const videoFormatOptions: DropDownOption[] = [
  { value: "mp4", label: "MP4 (H.264)" },
  { value: "webm", label: "WebM" },
  { value: "avi", label: "AVI" },
  { value: "mov", label: "QuickTime MOV" },
  { value: "mkv", label: "Matroska MKV" },
  { value: "flv", label: "Flash Video" },
  { value: "wmv", label: "Windows Media Video" },
  { value: "mpeg", label: "MPEG" },
  { value: "3gp", label: "3GPP" },
  { value: "ts", label: "MPEG Transport Stream" },
  { value: "m2ts", label: "MPEG-2 Transport Stream" },
  { value: "mxf", label: "Material Exchange Format" },
  { value: "ogv", label: "Ogg Video" },
  { value: "divx", label: "DivX" },
  { value: "rm", label: "RealMedia" },
  { value: "vob", label: "DVD Video Object" },
  { value: "mpg", label: "MPEG-1" },
  { value: "m4v", label: "M4V" },
  { value: "asf", label: "Advanced Systems Format" },
  { value: "f4v", label: "Flash F4V" },
];
